# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5ddcd3bd79f97ee9540d293a0031115"
name = "FreeGiftTiers"
application_url = "https://legislature-eastern-salary-skiing.trycloudflare.com"
embedded = true

# App Store Metadata
[app_store]
title = "FreeGiftTiers"
tagline = "Automated free gifts & tiered discounts to boost sales & customer loyalty"
description = "Transform your store's conversion rates with FreeGiftTiers, the comprehensive discount campaign app that automates free gift rewards and tiered promotions. Create engaging customer experiences that drive higher average order values and build lasting loyalty."
category = "Discounts"
subcategory = "Promotions - Other"
languages = ["English"]
works_with = ["Checkout", "Slide Carts", "Easy Bundles", "UpCart"]
support_email = "orders@mabelloveco.com"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_discounts,read_orders,write_cart_transforms,read_customer_events,write_customers,read_themes,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ "https://legislature-eastern-salary-skiing.trycloudflare.com/api/auth" ]
