name: Build and Test

on:
  push:
    branches: [ main, release/v1.0 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript type checking
      run: npx tsc --noEmit

    - name: Run ESLint
      run: npx eslint . --max-warnings=0

    - name: Build application
      run: npm run build

    - name: Check build output
      run: |
        if [ -d "build" ]; then
          echo "✅ Build successful - build directory created"
          ls -la build/
        else
          echo "❌ Build failed - no build directory found"
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build test
      run: npm run build

    - name: Verify production bundle
      run: |
        echo "Checking production bundle..."
        if [ -f "build/server/index.js" ]; then
          echo "✅ Server bundle exists"
        else
          echo "❌ Server bundle missing"
          exit 1
        fi
        
        if [ -d "build/client" ]; then
          echo "✅ Client bundle exists"
        else
          echo "❌ Client bundle missing"
          exit 1
        fi
